### ISSUE TITLE
dolphin: use same icon for "Hidden Files" toolbar entry as in maui

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#10]
in Netrunner, it should look like in Maui here:
![screenshot_20170214_155554](https://cloud.githubusercontent.com/assets/840070/22948372/86fde9d0-f2fe-11e6-8faf-083c197627ce.png)

**Comment by llelectronics** [comment]
Seems to be a left over as we have set an explicit "security-low" icon for hidden files before. Strangely it did not affect Maui. 
I now removed the icon set in the config so it should use the default one seen in the above screenshot.
