### ISSUE TITLE
sddm: install SugarDark Theme and set default https://store.kde.org/p/1272122/ 

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#100]
- sddm: https://www.opendesktop.org/p/1272122/

**Comment by llelectronics** [comment]
Added it: https://github.com/ds9-artwork/artwork-sddm-sugar-dark

**Comment by llelectronics** [comment]
Configured to be default: https://github.com/netrunner-common/netrunner-settings-sddm/commit/219cf377eb73cf5d0fc9f08d324b4b481e4f5aac

**Comment by star-buck** [comment]
works, now needs a bit finetune.
