### ISSUE TITLE
LibreOffice: Set Icons to "Tango"

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#105]

**Comment by llelectronics** [comment]
They are set to Tango by default.

**Comment by star-buck** [comment]
Not here, its set to Breeze, which is low contrast on Dark.

**Comment by llelectronics** [comment]
the lo-kde5 package seemed to adjust it :/

**Comment by llelectronics** [comment]
This should fix it: https://github.com/ds9-common/default-settings-applications/commit/64894702e5ebaa3038179985ee65915306b80419

**Comment by star-buck** [comment]
Yeah, doing one thing can affect another, so im testing and retesting
everything once again every time a change has been done.

**Comment by star-buck** [comment]
works
