### ISSUE TITLE
wallpapers: current ISO has weird wallpapers in /usr/share/wallpapers

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#106]
note sure where those come from, but remove marked wallpapers:
![screenshot_20181214_204929](https://user-images.githubusercontent.com/840070/50024169-cef9c500-ffe1-11e8-8b20-312b4010c152.png)

**Comment by llelectronics** [comment]
The bluebird, greybird stuff comes from the blackbird package which pulls them as recommends. As we don't use blackbird as gtk theme anymore It should be save to remove it from our packages and so the wallpapers won't be pulled.

**Comment by star-buck** [comment]
i have an idea: since i also see now multiple themes in GTK2 settings, those are probably xubuntu related gtk2 themes, and one of them is "Blackbird".
I assume a lot of xubuntu/blackbird/gtk themes have been pulled by accident, so by removing these again, the wallpapers and other stuff should be fixed again.
I will copy off the Blackbird theme though,as it is better then Breeze dark and matches Kvantum more. :) will open a new ticket about that.

**Comment by star-buck** [comment]
screenshot:
![screenshot_20181214_211344](https://user-images.githubusercontent.com/840070/50025258-2a798200-ffe5-11e8-84ad-e6c80462ba7f.png)
