### ISSUE TITLE
Localization: installing in German misses translations for Firefox, Krita

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#107]
so far Firefox , Krita.
gnome chess, thunderbird, lo, marble, skype gimp all were fine.
I might have missed still something will add then here in next comment.

**Comment by llelectronics** [comment]
Internet access was there during install? (this should take care of it in calamares if internet access is there: https://github.com/netrunner-desktop/calamares-desktop/blob/master/etc/calamares/modules/packages.conf#L8) 
As for Krita we need to add **krita-l10n** to the above.

**edit:** Firefox-l10n-* packages are missing from DCI. We need to add them from Sid
