### ISSUE TITLE
Snapshot DCI Next Repos and switch to snapshotted repos

### ISSUE THREAD

**Issue by llelectronics** [blue-systems/netrunner-issues-old#108]
Just as a placeholder to not forget snapshotting repos from DCI and switching to the snapshotted repos before releasing any final ISO.

**Comment by star-buck** [comment]
currently still this:
![screenshot_20181220_120131](https://user-images.githubusercontent.com/840070/50281220-0b4c7b80-044f-11e9-8e6c-8853d273ca5e.png)

**Comment by star-buck** [comment]
seems okay:
![screenshot_20181222_152302](https://user-images.githubusercontent.com/840070/50375432-7dfb5980-05fd-11e9-8d60-9cbca8c89fdf.png)
