### ISSUE TITLE
Firefox seems to still have an issue with dark themes (reading up some tickets for a possible fix)

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#110]
https://bugzilla.mozilla.org/show_bug.cgi?id=1283086
example sites:
bing.com
opendesktop.org/login

**Comment by llelectronics** [comment]
We applied a fix in Neptune for this forcing input and textfields to use the breeze light theme in config. We could do the same for Netrunner.
Only downside so far the search bar when searching on sites seems to be hard to read when it isn't finding the word.

All necessary is setting this 
`// For dark themes use light gtk input text fields`  
`pref("widget.content.gtk-theme-override", "elementary");`

**Comment by star-buck** [comment]
any screenshot example of the hard-to-read downside?

**Comment by star-buck** [comment]
there is also light font on white searchfield:
![screenshot_20181214_214708](https://user-images.githubusercontent.com/840070/50026610-e046cf80-ffe9-11e8-9b56-ddb63695b4b7.png)

**Comment by llelectronics** [comment]
![grafik](https://user-images.githubusercontent.com/3415572/50027163-9232cb80-ffeb-11e8-941e-2266b9bfc032.png)

**Comment by star-buck** [comment]
ah okay. needs to be tried to make a judgement, so i propose if there is no better solution at this moment to ship it next iso.

**Comment by star-buck** [comment]
seems to work great!
