### ISSUE TITLE
Firefox: opening a .deb file should suggest "Qapt", not Ark?

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#111]

**Comment by llelectronics** [comment]
It suggests Discover for me: 
![image](https://user-images.githubusercontent.com/3415572/50042475-93074400-0063-11e9-8be5-7cf665f43424.png)

**Comment by star-buck** [comment]
Discover is fine, though i wonder what happened to Qapt (or was it
debinstaller or something like that?)

**Comment by llelectronics** [comment]
The above commit changes it to use qapt-debinstaller instead of discover or ark.
