### ISSUE TITLE
Dolphin: single-click is changing with Looknfeel, e.g. Netrunner Default is doubleclick, Netrunner Black sets it to Singleclick

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#112]
maybe @notmart knows where this could be set?

**Comment by llelectronics** [comment]
Yeah I added it to Netrunner Desktop and Netrunner Black LNFs config to force set it to double click. If we remove the Netrunner Default that shouldn't be an issue anymore. Only the Netrunner Blue must be updated then.

**Comment by star-buck** [comment]
okay, will mark this green then and test with next iso.

**Comment by star-buck** [comment]
still not fixed. dolphin still uses singleclick under Netrunner Black LNF

**Comment by llelectronics** [comment]
This seems to be an upstream bug. As clicking on icons on the desktop does not open anything up and the config change "SingleClick=false" is applied correctly. Though I can confirm it not working for dolphin for some reason. 
After setting it in systemsettings to double click and changing the LNF then it works everytime for me btw.

**Comment by star-buck** [comment]
It is working for other LNF, so it must be possible for Black, too.

**Comment by star-buck** [comment]
Please ask in telegram then if you dont find the cause, difference from why
NetrunnerDesktop theme does change dolphin click behaviour.

**Comment by llelectronics** [comment]
I may have found the issue. The breeze-alphablack desktoptheme is also writing [KDE] section without a SingleClick=false in kdeglobals (to set its color scheme). That might interfere with whatever we write in our LNF. Changed it now in desktoptheme. Lets hope that fixes that issue on the next ISO.

**Comment by llelectronics** [comment]
Still broken in new ISO. More and more convinced this must be a bug somewhere not obvious to me. Will ask around

**Comment by star-buck** [comment]
Please ask around to get this fixed.

**Comment by llelectronics** [comment]
Seems to work on latest ISO

**Comment by star-buck** [comment]
seems fixed!
