### ISSUE TITLE
Yakuake error: couldnt apply blur/transparency

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#115]
error here,also one can see the add new window "+" is not rendered:
![screenshot_20181214_212127](https://user-images.githubusercontent.com/840070/50029764-26a12c00-fff4-11e8-8778-16a1e18efed4.png)

**Comment by star-buck** [comment]
![screenshot_20181214_230210](https://user-images.githubusercontent.com/840070/50029797-4fc1bc80-fff4-11e8-8816-fc8128ea7c59.png)

**Comment by llelectronics** [comment]
I noticed changing the LNF theme a few times breaks the visuals completely for yakuake.

**Comment by star-buck** [comment]
Okay, so will look how it works default right after install before changing
to non-black and back.

**Comment by star-buck** [comment]
seems fine the first time started, so closing this here
