### ISSUE TITLE
wallpapers: add new package and set new default (remove 1803 ones)

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#116]
will post link to zip here

**Comment by star-buck** [comment]
all wallpapers for this release:
https://www.dropbox.com/s/g0xbfaxnxwfdzhc/wallpapers-1901.rar?dl=0

**Comment by star-buck** [comment]
set default to blackbird.png

**Comment by llelectronics** [comment]
Done: https://github.com/netrunner-artwork/artwork-wallpapers-netrunner-1901-desktop
@shadeslayer please add this repo to dci so a package can be build.

**Comment by star-buck** [comment]
@llelectronics : you know how to add this yourself also, just in case for building the next ISO?

**Comment by llelectronics** [comment]
@star-buck no
**edit: shadeslayer will add it to dci soon**

**Comment by star-buck** [comment]
@shadeslayer : :+1:

**Comment by llelectronics** [comment]
Landed on new ISO. Default wallpaper is still wrong due to a typo. Fix for that landed already and will be hopefully there in next ISO.
