### ISSUE TITLE
Firefox: ublock: seems the filterlist is broken/not visible

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#117]
![screenshot_20181214_232346](https://user-images.githubusercontent.com/840070/50033159-a250a800-fff7-11e8-8174-0c50c0057bbc.png)

**Comment by star-buck** [comment]
this is back though.
filter is not applied to e.g. youtube, etc. re-opening.

What strikes me as odd is that first time opening Firefox right after install, ublock claims 0 blocked on google.com, but 422 or 21% since install... that smells of a non-clean mixed profile?

**Comment by llelectronics** [comment]
Looks fine for me: 
![image](https://user-images.githubusercontent.com/3415572/50280859-edcae200-044d-11e9-95aa-ad0f040109a9.png)

**Comment by star-buck** [comment]
after installation, it looks like the first screenshot.
Note that i installed in German, maybe thats another factor?

**Comment by star-buck** [comment]
![screenshot_20181220_120336](https://user-images.githubusercontent.com/840070/50281285-4c449000-044f-11e9-9ba6-044c6b7d4bd1.png)

**Comment by star-buck** [comment]
@notuxius : Please help test this by installing latest ISO in any other language than English or German.

**Comment by llelectronics** [comment]
Installed in german and filter list looks ok.

**Comment by star-buck** [comment]
this is broken, installed it 2xtimes now on metal hardware, no VM and its like in that screenshot not working as filterlists are broken.
I may have an idea what goes on, as depending on how this is all shipped, the profile doesnt get initialized correctly maybe because of
a) I name my user always "netrunner" and there may be a conflict or 
b) you name your user always the same and hence it works for you all the time, but as soon as you choose another username, it stops working as well (i have seen something personalized swap over to an install medium before in netrunner rolling, where there was a personal password set for github default from James since he mixed things as part of his personal profile over to the install skel or whatever - just saying it happens).

So to rule out a) or b) or both, I suggest trying to install with "netrunner" and confirm and I install with some other username and see if it either is the sa,e or solved.

**Comment by NuLogicSystems** [comment]
Have you looked under ~./mozilla/firefox to see if Firefox hasn't created a new profile instead of using our default one (but both are there)? 
I only ask because I've seen this happen a few times on my own system when trying to restore my own backed up profile ( ~./mozilla folder ), Firefox just doesn't always keep/follow the settings in my profiles.ini, and creates a new profile anyway.

**Comment by star-buck** [comment]
LIVE all is fine, installed with "netrunner" NOT.
Now it can only be that "netrunner" is special, therefore testing with other name now.

**Comment by llelectronics** [comment]
This is the only skel configuration file we ship for Firefox which sets the default filters: https://github.com/netrunner-common/netrunner-settings-firefox/blob/master/etc/skel/.mozilla/firefox/firefox.default/browser-extension-data/uBlock0%40raymondhill.net/storage.js
I fail to see how this configuration might be user specific.

**Comment by star-buck** [comment]
What do you mean? If a home isnt clean after install, its a bug anyone
could test. I am installing now again fresh with another user as netrunner,
but meanwhile any of you could do the above suggested test and see for
yourself.

**Comment by NuLogicSystems** [comment]
@llelectronics,
We also ship this: https://github.com/netrunner-common/netrunner-settings-firefox/blob/master/etc/skel/.mozilla/firefox/profiles.ini

My point was that, that I've noticed with more recent versions of Firefox, it sometimes completely ignores the settings in this file and creates a completely new profile. In other words, it might not be using firefox.default like it should.

@star-buck, I will download the ISO now and try on one of my spare laptops.

**Comment by star-buck** [comment]
absolutely confirmed current method doesnt work when installing with neither "netrunner" nor "starbuck" as user on bare metal neither english nor german.
@llelectronics :
I am absolutely sure when you install with user "netrunner" in "Deutsch", it will fail.

What strikes me as odd is that absolutely first time opening Firefox, ublock claims 0 blocked on google.com, but 422 or 21% since install... that smells of a non-clean mixed profile?
Any idea where to look or what to try?

**Comment by llelectronics** [comment]
We don't ship any profile though. 
So absolutely no idea whats going wrong here as in my tests it is working.

**Comment by NuLogicSystems** [comment]
I just installed on bare metal (HP pavilion TS 11) using netrunner as user name and password, the filter list is populated . My filters and My rules are also populated as expected. The ISO used was netrunner-20181221.1353-amd64.hybrid.iso

![screenshot_20181222_102852](https://user-images.githubusercontent.com/10186587/50377971-b139ea80-05f5-11e9-9206-022108d61a53.png)
![screenshot_20181222_102903](https://user-images.githubusercontent.com/10186587/50377972-b139ea80-05f5-11e9-87e7-deb8beb31153.png)
![screenshot_20181222_102912](https://user-images.githubusercontent.com/10186587/50377973-b139ea80-05f5-11e9-9ae2-b1bfc1b1393c.png)

**Comment by star-buck** [comment]
alright, maybe then the only idea have is that the calamares issue that prevents firefox to be translated is then also the cause for a faulty profile...
So possibly skipping one installation to test both tickets wasnt so good after all.
Will test again without that cala trick and see, meanwhile @NuLogicSystems can you do another installation in Spanish or German just to test FF?

**Comment by star-buck** [comment]
if that cala trick is indeed the cuplrit, the issue would start to become a blocker...

**Comment by NuLogicSystems** [comment]
Will do.

**Comment by NuLogicSystems** [comment]
OK, did a fresh install selecting Deutsche in Calamares, working as expected.
However, I did not change the keyboard settings.

**Comment by star-buck** [comment]
Okay, can you try once more in German, but first go ahead 2 pages in
english, then go back to first page in cala to change.

**Comment by adriaandegroot** [comment]
A new Calamares release (which would be 3.2.3) from master would be a disaster at this point, because it changes more settings, .. you get a cascade of changes that need re-testing. If this turns out to be a Calamares issue, I think a 3.2.2.1 will be needed (branching off of 3.2.2 tag) or a bit of a re-numbering. I'll give it a test as well on Sunday.

**Comment by NuLogicSystems** [comment]
OK, will do.

**Comment by NuLogicSystems** [comment]
OK, this time Firefox is in German, and yes the filters are populated.
![screenshot_20181223_005027](https://user-images.githubusercontent.com/10186587/50379587-7a76cb00-061b-11e9-8ad9-fe19a49cb371.png)

**Comment by star-buck** [comment]
i have a clue:
i installed this straight in english, no cala tricks, still got the same issue.
Now it seems not calamares related, but a race condition in how the profile materializes.
On both my slow HD machines, it is coming up BROKEN, as the profile shows first start these weird numbers of 422 blocks in the past:
![screenshot_20181223_115211](https://user-images.githubusercontent.com/840070/50385700-d2740700-06d9-11e9-9f50-ef337a8cf500.png)

Now simply deleting the .mozilla folder and starting ff again, everything is CLEAN and also works normally:
![screenshot_20181223_174152](https://user-images.githubusercontent.com/840070/50385713-2252ce00-06da-11e9-8644-49bfb962a93a.png)

I noticed thaton my SSD laptop, this isnt a problem, so it must be the way we "initialize" mozilla firefox and the profile folder.

**Comment by NuLogicSystems** [comment]
Skel gets copied when the user is created (adduser), so the Firefox profile is already there before first login.
When you first open Firefox it loads using our firefox.default profile. 
Firefox itself doesn't populate the ublock plugins list, firefox only loads the plugin itself.
I think it maybe the plugin itself that is taking a long time to populate it's list on the slower hardware.
On all my tests when I open the ublock plugins settings, that tab looks like your first pick, but only for about a half a sec, then the list populates.

**Comment by star-buck** [comment]
But those ate needed due to the damn google invisible shit they put there
in some google custom logos to only affect FF negatively.
Hence we need it and it needs to work somehow (like it worked on that slow
maxhine with Rolling 2018.08).

**Comment by star-buck** [comment]
still getting this and ublock filter not working in RC3:
![screenshot_20190103_154047](https://user-images.githubusercontent.com/840070/50643370-2e5a4d80-0f6e-11e9-9687-f518e0cdb9cb.png)

**Comment by star-buck** [comment]
it seems to work after editing the /etc/skel/.mozilla/firefox/firefox.default/extensions.ini and adding a new user to test.

**Comment by llelectronics** [comment]
FF should not read this file at all. Only FF-ESR though.

**Comment by star-buck** [comment]
True. 
Now I deleted .mozilla and started FF again to see when it actually works:
When it works, there is the storage.js under /browser-extension-data/ublock@Raymondhill.net and also correctly initialized folder /storage. When the filterlist is broken, I can delete the folder /storage and then FF starts to work.
It looks as if it sometimes fails to correctly initalize the storage.js and the "cache" under /storage inside the firefox default profile folder.

Is there any method to simulate using /etc/skel other than by adding a new user?
Any other idea how to initialize the ublockorigin addon other than that?

My guess is that while it copies over the storage.js file it does start building that /storage and when not copied over yet or not fully, the stuff under /storage is corrupt.

**Comment by llelectronics** [comment]
> When it works, there is the storage.js under /browser-extension-data/ublock@Raymondhill.net 

This is what we ship by default in /etc/skel (the configuration file for the servers and the custom rule for google) 

> correctly initialized folder /storage. When the filterlist is broken, I can delete the folder /storage and then FF starts to work.

So basically you confirmed a bug in the extension itself. 

> Is there any method to simulate using /etc/skel other than by adding a new user?

Just remove ~/.mozilla folder and cp -r /etc/skel/.mozilla ~/

> My guess is that while it copies over the storage.js file it does start building that /storage and when not copied over yet or not fully, the stuff under /storage is corrupt.

As we only ship the storage.js file which is a small one liner json file the issue in not correctly setting up the storage lies solely in the extension itself I fear. This needs further checking but from a first glance the /storage folders sqlite db for the ublock extension is not saving anything useful in there. It seems to be a default storage created for FF.

**Comment by star-buck** [comment]
Yeah, I spent the last four hours looking at this, adding users, trying to
find a state where it always works or always fails, but no success so far...
I am as far as imagining I may have noticed it does go from working to
broken just by restarting ff one more time.
Will do another round of testing tomorrow, but wondering if there is any
method in shipping ublock differently, as i even doubt its the special
filter rule what makes it fail.

Will try with the skel copy method, though i thought i did that before and
wondered if its exactly replicating what happens first time login/start ff.

Anyway, hoping to find a clue eventually while we wait for the snapshot
server to get fixed :)

**Comment by NuLogicSystems** [comment]
Could it be that your shipping an installed xpi instead of the installation xpi from the server?

Installed into user profile = uBlock0@raymondhill.net.xpi
From FF Plug-in server = ublock_origin-1.16.20-an+fx.xpi

It could also have something to do with linking from/usr/share/firefox/distribution/extensions to usr/lib/firefox/distribution/extensions.

If you use a usr/lib/firefox/distribution/extensions folder, then you'll need to remove the "Extensions": { settings from your policy.json file. If your policies.json Extensions setting is pointing to the /usr/lib/firefox/distribution/extensions, it can cause the extensions to be installed twice, or in parrellel, as any xpi file in the usr/lib/firefox/distribution/extensions folder is automatically installed regardless of these settings. This is why I didn't use a /usr/lib/firefox/distribution/extensions folder, on rolling.

This could also explain the storage.js file issue as well.

**Comment by star-buck** [comment]
Got maybe a clue: the storage.json is mostly overwritten and recompiled anyway, so sometimes this process fails and it results in a slightly smaller storage.js which then misses some lines.

Now I removed all the default lines and only left the user-filters in it, which then seems to work fine so far (tested 10xtimes, so not 100% sure yet, but much higher than before, where every 3rd skel copy failed).

Here is the new storage.js:
https://www.dropbox.com/s/lstam28kw33nkse/storage.js?dl=0

Somone please confirm this still works and I think we should ship it in RC4 then if nothing fails.

**Comment by star-buck** [comment]
further reduced storage.js that removed the stuff under "my rules":
https://www.dropbox.com/s/cvkctcw0rc2gwti/storage.js?dl=0

**Comment by star-buck** [comment]
Comparing working 1803 and 1901:

1803:
- FF Quantum 58 with cck2 and Plasmazilla
- ublock 1.15.10 via skel, which updates itself to 1.17.4 automatically without breaking
- no ff-integration addon

**Comment by star-buck** [comment]
RC7 still not fixed.

But following Zlatans advice, installing webext-ublock-origin package, then removing the own xpi shipped under /usr/share/firefox/... did come up fine 3 times in a row!
Having high hopes this one fixes it.

@llelectronics : remove shipped xpi+folders etc. +add webext-ublock-origin package from debian snapshot repo.

**Comment by NuLogicSystems** [comment]
The ublock_origin-1.17.4-an+fx.xpi I ship in the netrunner-rolling package is the webext verson from the Mozilla plugin store. I don't know what uBlock0@raymondhill.net.xpi is created from that ships in the netrunner-common version of this package.

**Comment by star-buck** [comment]
As long as it works in rolling, its fine. We will see that in next iso.

**Comment by llelectronics** [comment]
@NuLogicSystems we started from this xpi (just renamed) in the first place. The webext package of debian now does not ship a xpi but the extension extracted already. Maybe it really is able to fix stuff. Just added it as recommends and removed the xpi from netrunner-settings-firefox.

**Comment by NuLogicSystems** [comment]
@llelectronics Could also have been the fact that the xpi file was in the /distribution/extensions directory, in which Firefox installs every extension in this folder automatically (legacy), but also referenced and/or installed via the policies.json file. Just a thought. The webext-ublock-origin package uses some really strange directories, not sure it will be user removable via Filefox itself, but as long as it works.

**Comment by star-buck** [comment]
seems to have finally solved the issue.
@llelectronics : are both older methods mentioned by @NuLogicSystems now removed from new RC8 ISO?

**Comment by llelectronics** [comment]
Yes I removed them.
