### ISSUE TITLE
Add '-Web' string to all apps in 'Web' category in app menu

### ISSUE THREAD

**Issue by notuxius** [blue-systems/netrunner-issues-old#120]
Not just for Skype - for distinguishing them from regular installed apps during search for example - Telegram-Web, Whatsapp-Web

**Comment by star-buck** [comment]
Is there an official whatsapp app?

Otherwise its fine, its just skype we ship, so if not for that, i'd prefer
this without -web and more look into how to keep their opened task
distinguished and with their initial desktop icon(like prism did).
