### ISSUE TITLE
Don't use 'Shell' as Konsole/Yakuake profile name by default

### ISSUE THREAD

**Issue by notuxius** [blue-systems/netrunner-issues-old#121]
For changing Konsole/Yakuake appearance quickly without 'Sorry. Konsole does not have permission to save this profile...' error message

**Comment by star-buck** [comment]
Does it do this error for you? I never noticed this here so far.

**Comment by notuxius** [comment]
Selecting on 'Edit Current Profile...' in right click menu on Yakuake - then changing appearance settings shows next error for me:

![konsole-does-not-have-permission](https://user-images.githubusercontent.com/2657014/50046725-b2788e00-00b0-11e9-8354-7c3739d6e5f7.png)

**Comment by star-buck** [comment]
Not for me here. Did you install the iso?

**Comment by notuxius** [comment]
Yes, it's on installed system

**Comment by star-buck** [comment]
Try with the new iso and install, here its not possible for me to replicate.

**Comment by notuxius** [comment]
Tested with 14.12 in live and installed on VBox with same error

**Comment by star-buck** [comment]
the above screenshot is not installed, correct?
I doubt installed it gives an error as it should be then saved under .local/share/konsole.

**Comment by notuxius** [comment]
Video with error on installed system in VBox:
https://drive.google.com/open?id=1gxd94aoCxXkasGiurKuyrZt5nAbr5i_S
