### ISSUE TITLE
Printers KCM: not found

### ISSUE THREAD

**Issue by notuxius** [blue-systems/netrunner-issues-old#122]
![systemsettings-printers-shared-library-not-found](https://user-images.githubusercontent.com/2657014/50046561-e1413500-00ad-11e9-81e6-dbe19a5b96ee.png)

**Comment by star-buck** [comment]
Good spot, is this on latest iso?

**Comment by notuxius** [comment]
Yes, on installed 10.12 with updates and 13.12 live

**Comment by llelectronics** [comment]
Print Manager is apparently missing from Debian testing: https://qa.debian.org/excuses.php?package=print-manager
This 18.04 version from Sid is introducing two bugs that are critical (like delaying the start of plasma itself). That is the main reason why it did not land in testing.

**Comment by star-buck** [comment]
@shadeslayer @llelectronics : are those two bugs on our side, as in the kcm? We need to possibly patch and put the fixed deb in our own repos, in such a way that whenever the package officially lands in testing repo, it sueprseeds our version.
