### ISSUE TITLE
'Software Sources' isn't launching

### ISSUE THREAD

**Issue by notuxius** [blue-systems/netrunner-issues-old#124]
Steps:
1. Start Discover.
2. Open bottom left 'Settings' page.
3. Press top right 'Software Sources' button.

**Comment by notuxius** [comment]
Also not starting from mintUpdate -> Edit menu

**Comment by star-buck** [comment]
confirmed for both cases.

**Comment by llelectronics** [comment]
That did not fix it yet. python-apt is still complaining.

**Comment by star-buck** [comment]
@notuxius : can you confirm it is working now?

**Comment by notuxius** [comment]
Yes, Software Sources app is launching on updated installed sys and on latest (12.19) live iso
