### ISSUE TITLE
Differences in GRUB menu entries on BIOS and EFI systems

### ISSUE THREAD

**Issue by notuxius** [blue-systems/netrunner-issues-old#126]
Advanced options GRUB menu entry is displayed when launching Netrunner Debian in VBox (BIOS):
![grub-menu-advanced-options](https://user-images.githubusercontent.com/2657014/50047717-d09bb980-00c3-11e9-97e7-a2efa128d674.png)

but not when launching from USB drive on real HW (EFI)
memtest is displayed in GRUB menu when launching Netrunner Rolling in VBox (BIOS) but not when launching from USB drive on real HW (EFI)

**Comment by star-buck** [comment]
thats fine if it doesnt affect function. lets not go into these details between manjaro and debian upstream.
