### ISSUE TITLE
gtk2/gtk3-theme: change to "Blackbird"

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#133]
Blackbird themeing: https://www.dropbox.com/s/ysn6p9gca0o9f8l/Blackbird-gtk2-gtk3.tar.gz?dl=0

**Comment by llelectronics** [comment]
That looks like the blackbird that is already packaged in Debian. Or is there any change in it?

**Comment by star-buck** [comment]
Not yet, no, but for gtk-3 we may need an update or mix.

**Comment by llelectronics** [comment]
With the current dci issues I suggest staying at the debian version for now. We can always upload a newer version when necessary in our repository with a higher version number.
