### ISSUE TITLE
Kate: Toolbar: Add "Search" button at the end

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#138]

**Comment by llelectronics** [comment]
Seems to be not possible. I cannot add **find** or **search** to the toolbar:
![image](https://user-images.githubusercontent.com/3415572/50146632-7877d980-02b4-11e9-917c-5ebeea0345a7.png)

**Comment by star-buck** [comment]
You can choose the other toolbar from dropdown? Here it was easily possible.

**Comment by llelectronics** [comment]
Found it. Thx. Landed: https://github.com/ds9-common/default-settings-kdeapps/commit/2044d7989cd71cf5ec926553b5ac617684f697bc
