### ISSUE TITLE
apt spits out warnings about trusted.gpg

### ISSUE THREAD

**Issue by llelectronics** [blue-systems/netrunner-issues-old#139]
>     W: http://dci.ds9.pub/netrunner/dists/netrunner-next/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg are ignored as the file is not readable by user '_apt' executing apt-key.

>     W: http://snapshot.debian.org/archive/debian/20190101/dists/testing/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg are ignored as the file is not readable by user '_apt' executing apt-key.

 

>    W: https://repo.skype.com/deb/dists/stable/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg are ignored as the file is not readable by user '_apt' executing apt-key.

**Comment by llelectronics** [comment]
Can't reproduce on current live system. Strange

**Comment by notuxius** [comment]
Here it says that 'Software Sources' app may be the culprit https://lists.debian.org/debian-user/2018/02/msg00369.html
Upstream Debian https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=867681

**Comment by llelectronics** [comment]
Thanks very important finding. also for errata. it isn't a blocker for now as we ship the trusted keys in trusted.gpg.d folder and it only spits out warnings and no errors.

**Comment by star-buck** [comment]
this warning is crucial to get rid of though as it demonstrates a broken and potential dangerous system to any user even if they dont understand the implications.
So while not being a technical blocker, it is absolutely a psychological blocker seeing something like this:
![screenshot_20181222_152519](https://user-images.githubusercontent.com/840070/50375471-15f94300-05fe-11e9-9af9-fd8efc78891c.png)

**Comment by star-buck** [comment]
is this a viable workaround as suggested in one of the comments?
```
Deleting /etc/apt/trusted.gpg file and adding keys via apt-key workaroud the 
problem ...
```

**Comment by star-buck** [comment]
is this still correct/needed:
![screenshot_20181222_155021](https://user-images.githubusercontent.com/840070/50375770-23fd9280-0603-11e9-9bb0-729e0404dff4.png)

**Comment by llelectronics** [comment]
Yes this is still correct and needed. Those are the keys working. 
The issue is that synaptic is broken. Whenever you open it it breaks the trusted.gpg file.

**Comment by star-buck** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=867681
The bug report has 2 entries and is from mid-2017, so i strongly disagree that this isnt solved as otherwise this would mean millions of affected users and no one ignoring such a severe visual break.
This I didnt remember seeing any of these in last release 18.03 nor any of the ISOs in the beginning?

**Comment by star-buck** [comment]
"visually break", not functionality

**Comment by llelectronics** [comment]
That is the correct bug report for software-properties. I retested it with a clean install and as soon as I open software-properties-kde it creates the trusted.gpg file which is not readable by _apt and also if I make it readable by apt broken anyway. So the bug is still valid and not fixed yet.
Not opening software-properties and you won't have that issue.

**Comment by llelectronics** [comment]
Update. I tested with the debs from Ubuntu which seem to be way newer and they fix the handling of trusted.gpg. So using those the issue does not happen. 
I created a new software-properties github repo on ds9-extras providing the sources from ubuntu. 
@shadeslayer if you update dci to grab this new repo so it can build software-properties from there we can get this fixed.

**Comment by star-buck** [comment]
Great.
