### ISSUE TITLE
user profiles: disable/remove "Systemd Core Dumper" from showing up as user in sddm

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#145]

**Comment by llelectronics** [comment]
I added a commit this autumn which takes care of it: https://github.com/netrunner-common/netrunner-settings-sddm/commit/fce6747b6a52b41dd3d9a8ccd4227ebc393baeba

Is it still showing up for you? If yes is the /etc/sddm.conf looking like the one we ship by default?

**Comment by star-buck** [comment]
As soon as we switch sddm theme to one that shows the users with avatars
available "systemd core" is shown.
Hence I am rethinking sugarsddm tgeme and deciding on normal breeze, but
without blur (currently testing some options from the store).

**Comment by star-buck** [comment]
for a quick solution, we could switch back to simple sddm theme for 19.01

**Comment by llelectronics** [comment]
So the theme affects the issue? That would be a bug in SDDM as we ship a global /etc/sddm.conf file which sddm uses all the time. 
So far I failed to reproduce the issue. I switched themes and still only my normal user was showing up. 
Have you checked the /etc/sddm.conf file? 
Can you give me description on what you tried so I maybe am able to reproduce the issue.

**Comment by star-buck** [comment]
There is a systemdcore user visible in *every* theme that shows all user
profiles available.

**Comment by star-buck** [comment]
aside that, lets switch back to simple sddm for several reasons i found with sugar sddm, as its easier then fixing those last minute :/

**Comment by llelectronics** [comment]
I need the output of `grep systemd-coredump /etc/passwd` from the affected system. On my system it shows its UID to be 500. So it is hidden in every sddm theme.
