### ISSUE TITLE
[sambamounter]: entries in popup dialog vanish upon click

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#15]
https://www.dropbox.com/s/gztcyt9bj3g6z9w/sambamounter.mkv?dl=0

**Comment by aleixpol** [comment]
Confirmed:
I can reproduce in any directory dialog launched with `QFileDialog::getExistingDirectoryUrl(m_parent, QString(), openUrl, QFileDialog::ShowDirsOnly)`.

In fact, it can be reproduced with the following plasma-integration test:
`./qfiledialogtest --options ShowDirsOnly --selectDirectory remote:`

Need to investigate still why it happens.

**Comment by aleixpol** [comment]
Here's a fix: https://phabricator.kde.org/D8643

**Comment by star-buck** [comment]
@aleixpol : 
patch packaged and shipped, but still seems the same issue:
http://s3-eu-central-1.amazonaws.com/ds9-eu/dci/images/1710/amd64/netrunner-desktop/netrunner-20171103.2012-amd64.hybrid.iso

**Comment by aleixpol** [comment]
@shadeslayer Can you try this?
https://phabricator.kde.org/D8683
