### ISSUE TITLE
Rolling: FF toolbar issue

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#155]
@NuLogicSystems : any idea to fix that via an update?

**Comment by NuLogicSystems** [comment]
What are the toolbar issues?

**Comment by NuLogicSystems** [comment]
Never mind I think I found the issue and fixed it here:
https://github.com/netrunner-rolling/netrunner-settings-firefox/commit/9153f8366aedac585dc483e242bcc138aacb991d

**Comment by NuLogicSystems** [comment]
Fixed in rolling, but I think the same problem may exist in the netrunner-common/netrunner-settings-firefox.

**Comment by llelectronics** [comment]
Thx also applied for netrunner-common/netrunner-settings-firefox
