### ISSUE TITLE
install ocs-url package (by making it available under own repo extras)

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#161]
program: https://www.opendesktop.org/p/1136805/
set FF association default:
![screenshot_20190107_220136](https://user-images.githubusercontent.com/840070/50793279-f5044380-12c7-11e9-86de-732ceac3c95d.png)

**Comment by star-buck** [comment]
that should also fix #153

**Comment by star-buck** [comment]
the package is installed and works!
Now can we do also the second part, that is having the mimetype already associated with ocs default (like we did by  open qapt instead of ark for deb packages)?

**Comment by llelectronics** [comment]
The ocs:// mimetype is associated already with it by default.

**Comment by star-buck** [comment]
I mean the firefox filetype or whatever its called, so it doesnt ask to
search for a program anymore.
