### ISSUE TITLE
FF: associate firefox ocs:// to ocs-url program

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#163]
![screenshot_20190107_220136](https://user-images.githubusercontent.com/840070/50793279-f5044380-12c7-11e9-86de-732ceac3c95d.png)

**Comment by llelectronics** [comment]
Done: https://github.com/netrunner-common/netrunner-settings-firefox/commit/231ee4aa259c115d07f00e3f78a0d228ac98009d
