### ISSUE TITLE
DCI repos cleanup

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#17]
@shadeslayer : 
since we released "netrunner-1710", can we remove the "netrunner-1709" here:
http://ds9-eu.s3-website.eu-central-1.amazonaws.com/#!/dci%2Fpackages%2Fnetrunner%2Fdists%2F

Also rename netrunner-1801 to netrunner-1803

**Comment by star-buck** [comment]
same here:
http://ds9-eu.s3-website.eu-central-1.amazonaws.com/#!/dci%2Fimages%2F

**Comment by shadeslayer** [comment]
I've removed it from the server as you can see here : http://dci.ds9.pub/netrunner/dists/

But I guess aptly doesn't remove the files from S3, just stops referencing them

**Comment by shadeslayer** [comment]
1801 will be renamed to 1803 in the upcoming days since I have to update it in multiple other places.

**Comment by star-buck** [comment]
?????
http://ds9-eu.s3-website.eu-central-1.amazonaws.com/#!/dci%2Fpackages%2Fnetrunner%2Fdists%2F

**Comment by star-buck** [comment]
How to get rid of them on S3?

**Comment by shadeslayer** [comment]
Gone now
