### ISSUE TITLE
Netrunner distribution isn't searchable when selecting arm64 architecture on Distrowatch

### ISSUE THREAD

**Issue by notuxius** [blue-systems/netrunner-issues-old#172]
Search page: https://distrowatch.com/search.php
Selecting armhf architecture works, looks like they renamed aarch64 into arm64

**Comment by llelectronics** [comment]
This is an issue of distrowatch I would say. Not sure how we should deal with it.

**Comment by notuxius** [comment]
Can we change Netrunner architecture from aarch64 to arm64 on Distrowatch?

**Comment by llelectronics** [comment]
aarch64 is arm64 not sure what distrowatch does there. Of course we can always contact distrowatch and ask kindly.

**Comment by star-buck** [comment]
Its nothing we ever entered ourselves there.
You can superfriendly ask or forget it.

**Comment by notuxius** [comment]
Wrote to Distrowatch

**Comment by notuxius** [comment]
Done, also fixed KDE neon arm search
