### ISSUE TITLE
Netrunner 18.03 ARM64 IMG doesn't boot from SD card on Pinebook

### ISSUE THREAD

**Issue by notuxius** [blue-systems/netrunner-issues-old#173]
Only black screen is shown

**Comment by star-buck** [comment]
What kind of pinebook do you have?

**Comment by star-buck** [comment]
Did you extract the img?
It could be anything, from the sdcard to the wrong tool you burned this.

**Comment by notuxius** [comment]
Extracted the image, Pinebook 11.6″ IPS 1080p 2gigs or RAM, tried with Gnome Disks and dd utility, also tested Manjaro ARM with these utilities and it's launched on the Pinebook

**Comment by star-buck** [comment]
Its a different pinebook, simple as that. Please close this ticket.
