### ISSUE TITLE
Rolling: doesnt shutdown completely (power button light stays on, fan still running)

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#184]

**Comment by NuLogicSystems** [comment]
Is your system still freezing after updating systemd to the latest RC in testing?

**Comment by star-buck** [comment]
Cant say, as i already "overinstalled" last install. :)

**Comment by star-buck** [comment]
it now works with RC

**Comment by NuLogicSystems** [comment]
Yea, Manjaro is playing around with pre-release builds of systemd, mesa and who knows what else in the testing branch atm.
