### ISSUE TITLE
Rolling: wallpaper dialog: color scheme is not applied correctly

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#189]
this is how it looks, even though Netrunner Black is selected:
![Screenshot_20190413_144629](https://user-images.githubusercontent.com/840070/56080096-fc724600-5dfc-11e9-8df0-021a5cfdb8c4.png)

simply re-applying seems to fix it:
![Screenshot_20190413_144720](https://user-images.githubusercontent.com/840070/56080100-02682700-5dfd-11e9-9fc8-325b509d0204.png)

even weirder: it does look normal when in LIVE mode, just when installed it seems not applied.

@llelectronics : since it works in debian, maybe we do something slightly different there?

@notmart : any idea where too look out for? maybe look and feel is not correctly set?

**Comment by llelectronics** [comment]
Again another indicator for me that LNF is not applied correctly for some reason on the installed system. It seems to use a mixed configuration causing this and the other issues (like panel size)

**Comment by star-buck** [comment]
Panel size seems to work now, at least on that machine.
Still something seems differently applied or loaded in live mode vs.
Installed.

**Comment by NuLogicSystems** [comment]
That's odd, I just installed my AMD laptop at home with the RC3 ISO and didn't have this issue.
However, on that laptop I get some graphic glitches on the borders with kvantum/aurora themes, changing the opengl setting to 3.1 fixes that though.

@llelectronics,
There is no difference in the live user and the installed system users settings. The only differences in the live overlay is Calamares is present, and a few tweeks from Manjaro that have nothing to do with themes. In both cases the users home directories are created at login, albiet in the live session, the live users home directory is created in ram, and on the installed system the users home directory is created on the physical hard drive.

**Comment by star-buck** [comment]
Then it seems random? This happened on a very slow hdd machine, so not sure
if its reproducible there or really random, will try again.
