### ISSUE TITLE
How does Debian version has everything translated after install?

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#190]
reason is to find out why Rolling has not all packages translated.
So maybe there is some calamares module settings that we could add to Rolling to allow installing missing language packs e.g. for Firefox during install when connected to internet?

@llelectronics : anywhere for @NuLogicSystems to look at a repo to figure this out?

**Comment by llelectronics** [comment]
We use the try_install option of the packages module. 
@NuLogicSystems see https://github.com/netrunner-desktop/calamares-desktop/blob/master/etc/calamares/modules/packages.conf 
${LOCALE} is set to whatever you set as language in the installer. Be aware of the **\*** to catch something like de-DE in package names or pt-Br and so on.

**Comment by star-buck** [comment]
Thanks Leszek!
I decided to release Rolling now. We can still do rc7, rc8 etc., so in case
we get something fixed or calamares to install languages, we can always do
a 2019.04.1 release update.
