### ISSUE TITLE
Firefox: we do have some settings LOCKED, this needs to be solved differently via about:config like all the other ones

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#193]
seen on rolling, not sure if it affects Debian as well:
![Screenshot_20190422_190044](https://user-images.githubusercontent.com/840070/56512951-29c3a000-6531-11e9-8489-a8d4561cef65.png)

**Comment by NuLogicSystems** [comment]
I'll have to look at it again, but there are some settings that upstream firefox removed the ability to change via autoconfig citing their redistribution policies. This is part of the reason cc2 no longer works, and why adding the enterprise policies.json was needed.

**Comment by NuLogicSystems** [comment]
I just looked and we did not lock these, they must have been locked by upstream Firefox.
https://support.mozilla.org/en-US/kb/customizing-firefox-using-autoconfig#w_functions-of-autoconfig

**Comment by star-buck** [comment]
Very unlikely. Why would they lock the startpage? They are rather locked by
us somehow shipping something in a way that those are no longer editable.

**Comment by NuLogicSystems** [comment]
I don't see the startpage being locked, only the overide and welcome urls.

**Comment by NuLogicSystems** [comment]
I do know that Firefox 57 and above no longer allow the startpage to be changed:
https://support.mozilla.org/en-US/kb/firefox-default-home-page-has-links-to-features

**Comment by star-buck** [comment]
Yeah, its weird, the startpage can be changed, but not the newtab page.
Lets leave it there, im just seeing google.com startpage using 2-8% cpu
time just displaying it again. Im just glad its not preloaded, otherwise we
would need to decide to switch to a new startpage or explicitly add
about:newtab as startpage url under "Home" settings.

**Comment by NuLogicSystems** [comment]
Yes, there was an announcement about not being able to change the new tab page as well. I just can't find it again atm.
