### ISSUE TITLE
Clarify the relationship between Netrunner and Maui Linux

### ISSUE THREAD

**Issue by probonopd** [blue-systems/netrunner-issues-old#2]
I was under the impression that the future of Netrunner was Maui Linux, but apparently I was wrong. Hence it would be good to clarify the relationship between Netrunner and Maui Linux.

**Comment by star-buck** [comment]
Simple: Ubuntu flavor is now Maui, Netrunner versions based directly on
Debian continue (core, odroid, desktop) under the Netrunner brand.

**Comment by probonopd** [comment]
And which should I use? ;-)

**Comment by star-buck** [comment]
Depends of course what you need... ppas , driver manager, etc. = maui, if
you can do most things manually, and want an even more stable base, then
debian...

**Comment by probonopd** [comment]
Thanks
