### ISSUE TITLE
Debian: resolve the error message from apt, so it no longer shows the warning at each transaction

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#22]
![screenshot_20180114_112853](https://user-images.githubusercontent.com/840070/34919862-3ceede40-f91e-11e7-84ae-3ebf3054c118.png)

**Comment by llelectronics** [comment]
This is a warning by apt that your kernel or system does not support the seccomp policy. It is actually not an error and I am not sure why synaptic does pick up warnings. In my opinion it should not and even if it does not in that way at least. 

As I don't have a system with that behavior to test here. Can you try disabling seccomp support in general to see if it solves the issue on that particular system. As root please execute
`echo 'apt::sandbox::seccomp "false";' > /etc/apt/apt.conf.d/999seccomp`

And run apt-get update afterwards and try again in synaptic. 
In general seccomp support is nice as it would run stuff in a sandbox like environment. So more security here. The maintainer of apt says this warning will get away in future versions.
