### ISSUE TITLE
FF: TICK Make Browser default

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#23]

**Comment by NuLogicSystems** [comment]
Firefox 57 no longer reads, or writes from kdeglobals, it's now only using mimeapps.lst.
This probably has something to do with not having the KDE patched version.

We'll need to adjust our packaging accordingly.

**Comment by llelectronics** [comment]
I can't remember us setting anything in firefox config for that. We only set it as default in kdeglobals and mimeapps.list 
The debian and ubuntu builds have the dialog in firefox disabled by default that asks for setting the browser as default.

**Comment by NuLogicSystems** [comment]
Where is the mimeapps.list in git?
I'm pulling mostly from the ds9 and netrunner github repositories for packaging in rolling.
All I can find is the kdeglobals, which the non-KDE patched version of Firefox does not use.

**Comment by llelectronics** [comment]
You can find our mimeapps.list here though yeah under further inspection we don't specify firefox as html extension handler as kdeglobals settings takes care of it https://github.com/ds9-common/default-settings-applications/blob/master/usr/share/default-settings/plasma5-profile/mimeapps.list

**Comment by NuLogicSystems** [comment]
OK, then I'll pull the settings from my test system and fix this.
Thanks..

**Comment by NuLogicSystems** [comment]
Fixed:
https://github.com/ds9-common/default-settings-applications/commit/c82f94c6f231b730e3fcb370fcd6223c9d95d335

**Comment by NuLogicSystems** [comment]
It turns out that Firefox actually looks for gconf settings:
https://github.com/netrunner-rolling/netrunner-settings-firefox/tree/master/etc/skel/.config/gconf/desktop

However, it sets all three (gconf, kdeglobals and mimapps.lst) when the button is pushed.
