### ISSUE TITLE
Thunderbird Lightning doesnt work and makes the program quit if calendar button is clicked

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#3]
![screenshot_20161104_194929](https://cloud.githubusercontent.com/assets/840070/20018467/1c2d07a2-a2c8-11e6-8c6e-75175bbca27b.png)

**Comment by llelectronics** [comment]
We fixed that in Maui by removing the extension from the profile and relying on xul-ext-lightning package that gets build from the thunderbird source.

**Comment by shadeslayer** [comment]
I think Netrunner Desktop didn't get the fix because we haven't snapshot'd the ds9-common repo which has the fix. I'll look into it.

**Comment by shadeslayer** [comment]
Snapshotted, if you remove the plugin and install the package this will be fixed, should also be fixed in the next ISO

**Comment by shadeslayer** [comment]
Should I close this?

**Comment by star-buck** [comment]
Yes, can be closed.
