### ISSUE TITLE
Rock64: novnc only works with IP-adress:5900, not "live-pc:5900"

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#32]

**Comment by llelectronics** [comment]
I fear it might be an issue with your particular DNS cache of your router or browser. 
It works fine for me and is accessible via live-pc. 

On Chromium I removed the dns cache by accessing: chrome://net-internals/#dns and clearing it.
On Firefox you can clear the cache in settings -> security

At least I can access live-pc:5900 which gives me a directory listing where I can click on vnc_auto.html 
But in general there is still an issue as it won't connect that way. Entering the IP Address then it works and connects fine. I'll investigate further.

**Comment by llelectronics** [comment]
**Update:** Found out editing /etc/nsswitch.conf and removing the NOTFOUND and mdns4 stuff makes dns resolving via avahi 200% faster than before. Starbuck would be nice if you could test this change to see if it fixes the issue for you too before we include it in one of the next images.
