### ISSUE TITLE
Rock64: vnc-browser window is tiny

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#33]
![snap 2018-05-01 at 12 09 32](https://user-images.githubusercontent.com/840070/39469447-8a90c08c-4d38-11e8-9e42-9ab7b2c024b6.png)

**Comment by star-buck** [comment]
but at least yakuake comes up fine ;)
![snap 2018-05-01 at 12 10 54](https://user-images.githubusercontent.com/840070/39469481-bd0f341c-4d38-11e8-8e67-a48e1ff7a25d.png)

**Comment by llelectronics** [comment]
@shadeslayer we had a fix for this before. Seems like it is either not working with the kernel (we used a different one you injected manually before) or we need some workaround for this.

**Comment by shadeslayer** [comment]
I think the gfx acceleration setup is screwed up. Will take a look at it when I'm back in Barcelona.

**Comment by llelectronics** [comment]
Just as info as it is working fine for me. With attached hdmi cable to a monitor which is turned on it gets the correct resolution.

**Comment by llelectronics** [comment]
This commit forces the minimum resolution to 800x600 https://github.com/netrunner-zeronet/rock64-live-build-zeronet/commit/98ff789c69b54fe22b6ab5e230629fe0d9ee5d59

**Comment by star-buck** [comment]
Can we spin a new img so i can test all changes?
