### ISSUE TITLE
Rock64: move 0toggle widget from desktop to panel

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#34]
move here:
![snap 2018-05-03 at 15 29 57](https://user-images.githubusercontent.com/840070/39579417-032cd2b0-4ee7-11e8-9856-f4ab2549a7a9.png)

**Comment by llelectronics** [comment]
Done with: https://github.com/netrunner-artwork/artwork-lnf-netrunner-zeronet/commit/75baca13a88309893fb1cb06035c23f2f754b060
