### ISSUE TITLE
Rock64: port map 80 to 43110

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#36]
`sudo iptables -A PREROUTING -t nat -p tcp --dport 80 -j REDIRECT --to-ports 43110`

**Comment by llelectronics** [comment]
This package https://github.com/netrunner-zeronet/netrunner-zeronet-iptable-settings should take care of it by providing a config file that gets automatically loaded when **iptables-persistent** package is installed.
