### ISSUE TITLE
Rock64: after power-reset reboot, can start auto_vnc on :5900 but then get connection timeout

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#39]

**Comment by star-buck** [comment]
this is what is running on the odroid c1:
![snap 2018-05-03 at 18 03 54](https://user-images.githubusercontent.com/840070/39588703-980b37d6-4efc-11e8-96fc-b928cf4fe2b0.png)

**Comment by llelectronics** [comment]
Yes we have dozens of those aswell on the rock64

**Comment by llelectronics** [comment]
Disabling IPv6 listening for x11vnc helps here in my tests. At least I could reliably connect after a hard reboot. 
Should be fixed with this: https://github.com/netrunner-common/netrunner-settings-autostart/commit/140fa09825af76c3b8ca03129dda1b19fc2ea355
