### ISSUE TITLE
Rock64: soft-reboot doesnt work, machine doesnt shutdown properly

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#40]

**Comment by llelectronics** [comment]
I tested now 3 kernels. 
First the ayufan kernel we ship 4.4.114
then the armbian 4.4.124 and the ayufan 4.4.120 

all show the same behavior and panic on reboot. 

So shutdown is working but when the machine comes up the kernel panics a few seconds after. 
This is the log I got: https://dpaste.de/vr8h
