### ISSUE TITLE
Netrunner: FF: ship https://addons.mozilla.org/en-US/firefox/addon/plasma-integration/ ; disable systray info

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#45]

**Comment by shadeslayer** [comment]
I believe @ScarlettGatelyClark is working on packaging this?

**Comment by NuLogicSystems** [comment]
I'll add it to my "netrunner-settings-firefox" package for rolling on my next set of updates.

**Comment by NuLogicSystems** [comment]
Looks like I'll also need to pull this from the AUR and package it as well:
https://aur.archlinux.org/packages/plasma-browser-integration/

Quote:

> The plasma-browser-integration package must be installed for this extension to work. It will be available from your distribution's package manager.

**Comment by ScarlettGatelyMoore** [comment]
(Sorry was on vacation )
Well, I started to, claimed the ITP, but saw chatter in debian-qt-kde channel about someone in mentors working on it, so I wandered off. This was last month and I do not see it uploaded or anything, so I am trying to get a status and try to claim it again, and go from there.

**Comment by star-buck** [comment]
@NuLogicSystems : is that in? Because Plasma still points to it from the systray...
maybe we can disable that.

**Comment by NuLogicSystems** [comment]
Both should be installed.
What systray info are you referring to exactly?
I don't see anything in my tray for this extension, can I get a screen shot?

**Comment by ScarlettGatelyMoore** [comment]
The version in Debian has systray disabled. Maxy will upload with plasma.
