### ISSUE TITLE
Desktop Effects: Transparency: set blur and noise strength 

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#49]
set like this:
![screenshot_20180629_100158](https://user-images.githubusercontent.com/840070/42087452-c01d4d12-7b85-11e8-808a-007bd62d30e9.png)

**Comment by NuLogicSystems** [comment]
Done for rolling

**Comment by llelectronics** [comment]
@NuLogicSystems can you add links to the commits when you fix something. We might want to sync your work for Netrunner (Debian base) aswell :)

**Comment by NuLogicSystems** [comment]
I did in the pkgbuild here:
https://github.com/netrunner-rolling/PKGBUILD-netrunner-common/commit/bedc02f922a9ca1a93faec4f27f138d8474b2da8

Mainly because netrunner common doesn't have the blur effect enabled like rolling does.

**Comment by llelectronics** [comment]
Ah ok thx :)

**Comment by star-buck** [comment]
@NuLogicSystems : It is not done on rc1.

**Comment by NuLogicSystems** [comment]
I set them. Let me take another look.

**Comment by NuLogicSystems** [comment]
I see what I did wrong, it's fixed in updated package.
https://github.com/netrunner-rolling/PKGBUILD-netrunner-common/commit/768db21e3c004b9dabe42815b2b09658c11332f3

**Comment by llelectronics** [comment]
Commit landed here: https://github.com/netrunner-common/netrunner-settings-theming/commit/3e8a5d1770a83762eaedaa49f7c968f97cb3b8a5
