### ISSUE TITLE
Desktop Effects: Enable "Background Contrast"

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#50]

**Comment by NuLogicSystems** [comment]
Done for rolling

**Comment by star-buck** [comment]
@NuLogicSystems : it is not done on rc1.

**Comment by NuLogicSystems** [comment]
I now have the changes all sorted out now:
https://github.com/netrunner-rolling/PKGBUILD-netrunner-common/commit/a2aa0fe9c214e5f39aec00b51350c0d3831ed51a

**Comment by llelectronics** [comment]
Landed here: https://github.com/netrunner-common/netrunner-settings-theming/commit/0887bd7110fd6cec4c000010e555f30287508340
