### ISSUE TITLE
Firefox: add ublock blocking rule due to "google hidden throbber under linux"

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#51]
@NuLogicSystems : seems this is missing again in latest rolling beta2:

add to "ublock - My filters":
```
www.google.*###cnsm` > g-loading-icon
google.*###cnsm > g-loading-icon
```

see here: https://github.com/netrunner-rolling/2018.01/issues/40

**Comment by NuLogicSystems** [comment]
Fixed for rolling here:
https://github.com/netrunner-rolling/netrunner-settings-firefox/commit/8ee2e9ea3a366fbd8fac7878c4f9fc77de5f2ab7
