### ISSUE TITLE
Desktop Effects: Animation speed: set to +1 above instant

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#53]

**Comment by NuLogicSystems** [comment]
Done for rolling:
https://github.com/netrunner-rolling/PKGBUILD-netrunner-common/commit/02b5c5ec292e367d0eb84df31d6026bcdc708de8

**Comment by llelectronics** [comment]
Landed here: https://github.com/netrunner-common/netrunner-settings-theming/commit/0c4917fbceb028d0f48946f6ddef4c448354f171
