### ISSUE TITLE
Rolling: Kamoso is missing FX? I think kipi-plugin is needed...

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#55]

**Comment by NuLogicSystems** [comment]
OK, I'll add it for next ISO.
I see what happened, it was listed as a digikam extra package and the Kamoso package dosent list it as a dependancy at all.

**Comment by NuLogicSystems** [comment]
Done

**Comment by star-buck** [comment]
please mark with green label "Rolling"
