### ISSUE TITLE
Idea: add "Web" top level menu category plus some "Web-Apps" with icons that link to pages

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#59]
I know we had looked and tried some apps before, I just can't seem to find the ticket (or it was done in person without ticket system), so here is one opened:

- add "Web" top level menu and have it sorted correctly to the bottom (A-Z sorting is on).
- add Whatsapp: https://web.whatsapp.com/
- add Telegram: https://web.telegram.org/

Both launchers should open firefox in its own process and if possible retain displaying their assigned icon in taskmanager to keep them seperate.

**Comment by star-buck** [comment]
an email from Eike regarding that topic:

> (1)
> 
> Change desktop file:
> - Use `firefox --class hooktube` instead of xdg-open in Exec=
> - Add StartupWMClass=hooktube to .desktop file
> 
> Effect:
> Icon will be taken from hooktube.desktop file both for startup
> notification and final task.
> 
> Problem:
> If you launch Firefox from its launcher you get a second window. Since
> there's an existing instance, and Firefox' code is meh, it will continue
> to use the passed --class for the second window, so the seperate Firefox
> task also has the same task icon.
> 
> (2)
> 
> Change desktop file:
> Set StartupNotify=true to false
> 
> Effect:
> No startup notification for hooktube, Firefox will just pop up with it open
> 
> 
> I can't think of any other options, sorry. If StartupNotify is on, then
> KRun will simply create a startup notification for that .desktop file,
> which doesn't match the resulting Firefox window. There's no way to
> override what KRun does there, which makes sense - of course it creates
> a notification for the .desktop file you're using.
> 
> (1) would in theory be nice if Firefox was smart enough never to reuse
> an instance with a different WMCLASS (or at least not reuse the WMCLASS
> on further windows) so you could have a proper fully seperate Hooktube
> task. (This is how Chrome web apps work.) Alas, Firefox isn't that smart.
> 
> There may be some workarounds, but it's not super efficient for me to
> investigate this in particular since it's not really TM-related:
> 
> https://www.reddit.com/r/firefox/comments/5wrnsj/is_there_a_app_mode_in_firefox/?st=jg5ej2ah&sh=b78a9b2f
>

**Comment by star-buck** [comment]
works okay so far when adding the package.

**Comment by star-buck** [comment]
needs to be added to Rolling

**Comment by NuLogicSystems** [comment]
I packaged and added what was already in ds9-extras, with no changes on my end.
https://github.com/ds9-extras/web-menu-entries/tree/master/usr/share/applications
Shouldn't those changes need to be made there?
