### ISSUE TITLE
Rolling: update issue breeze-kde4-netrunner

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#60]
> [netrunner@netrunner-pc ~]$ sudo pacman -Syu
> :: Synchronizing package databases...
>  core is up to date
>  extra is up to date
>  community is up to date
>  multilib is up to date
>  netrunner is up to date
> :: Starting full system upgrade...
> :: Replace ca-certificates-cacert with core/ca-certificates? [Y/n] 
> :: Replace kuiserver with extra/plasma-workspace? [Y/n] 
> :: Replace libx264 with extra/x264? [Y/n] 
> :: Replace libx264-all with extra/x264? [Y/n] 
> :: Replace pulseaudio-gconf with extra/pulseaudio? [Y/n] 
> :: Replace qca-qt5 with extra/qca? [Y/n] 
> resolving dependencies...
> looking for conflicting packages...
> error: failed to prepare transaction (could not satisfy dependencies)
> :: unable to satisfy dependency 'breeze-kde4' required by breeze-kde4-netrunner
>

**Comment by star-buck** [comment]
if removing the "breeze-kde4-netrunner", the update works fine.
Can we automatically force remove this so people don't have to worry or guess?

**Comment by NuLogicSystems** [comment]
We needed the meta package to switch back to the upstream breeze-kde4 when our patches would no longer apply. Since then Manjaro dropped all *-kde4 packages from their repository, this includes breeze-kde4. Just removing the breeze-kde4-netrunner meta package from our repository will not fix this.
Let me take a look into what can be done to correct this issue.

**Comment by NuLogicSystems** [comment]
Actually, Arch is where breeze-kde4 was delegated to the AUR, and dropped from their repository.
However, this would not be an issue for anyone that used the 2018.08 ISO, or that had updated their system before the breeze-kde4 package had been removed.

**Comment by NuLogicSystems** [comment]
I can't force remove the package, but I can change it to require breeze instead of breeze-kde4 thus circumventing the problem.

**Comment by NuLogicSystems** [comment]
OK, I updated the breeze-kde4-netrunner meta package. This will no longer cause a problem for anyone that hadn't updated their system prior to the breeze-kde4 package removal by upstream.

**Comment by star-buck** [comment]
Good, thanks.
