### ISSUE TITLE
FF: flash plugin doesnt work

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#64]
![screenshot_20181201_055432](https://user-images.githubusercontent.com/840070/49327298-d32bda00-f52d-11e8-83fc-432e7a05d93b.png)
tested here:
https://www.quirksmode.org/html5/tests/video.html
example video on twitter:
![screenshot_20181208_172331](https://user-images.githubusercontent.com/840070/49688173-52ad4080-fb0e-11e8-9ece-e9580d71755f.png)

**Comment by llelectronics** [comment]
Flash is a deprecated technology therefor Click to play is enabled by default in firefox. If you click on "Run Adobe Flash" it should load flash (and maybe fail because of something else being shitty on that site)
