### ISSUE TITLE
Firefox: "opening with": doesnt work

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#67]
When opening for example .sh or .txt files, the popup displays a dropbox with an empty field and when dropping down it says "Other" instead of "Kate"... when clicking "Okay" it does open Kate though.

It is worse for not yet defined types, like "Appimages", where "Browse" to select a program simply does nothing:
![screenshot_20181201_124715](https://user-images.githubusercontent.com/840070/49331228-b90eed80-f567-11e8-8117-514c52a07f99.png)

**Comment by llelectronics** [comment]
I tested this links text files and it works as expected. Showing "kate" as default for opening the file. 
https://sample-videos.com/text/Sample-text-file-10kb.txt
For appimages it is normal to not show anything as long as appimagelauncher isn't installed (and that is another issue to get that compiled at all). Clicking browse is indeed doing nothing.

**Comment by star-buck** [comment]
Clicking browse doing nothing is the main issue here.

**Comment by llelectronics** [comment]
Tested with plasmazilla ff build. There it works. So I think rebuilding the firefox package with plasma integration patches should work. Though I don't think it can be build via the CI system yet. (at least we had problems with it in the past) 
**Update:** Manual building also fails as cbinding package is missing from Debian Testing currently.

**Comment by star-buck** [comment]
also opening a deb file now resorts to Ark...
