### ISSUE TITLE
dolphin: right sidebar: configuration is reset again :/

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#69]
configuration should be this:
![screenshot_20181201_140450](https://user-images.githubusercontent.com/840070/49331887-2aec3480-f572-11e8-8646-41a61ee7f54a.png)

**Comment by llelectronics** [comment]
Added the configuration file: https://github.com/ds9-common/default-settings-kdeapps/commit/1f8962074ad8343c2b1e573408966de7f6e3f6d0
