### ISSUE TITLE
[ds9-extras-packaging]: groupingplasmoid

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#7]
Please package this in Extras (make available as ususal through backports):
https://cgit.kde.org/scratch/davidedmundson/groupingplasmoid.git/

**Comment by shadeslayer** [comment]
Done too.

**Comment by star-buck** [comment]
This is now shipped standard in 5.9, isnt it?

**Comment by llelectronics** [comment]
Yes it is part of Plasma since 5.9
