### ISSUE TITLE
fonts: hinting: set to RGB, Slight

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#71]
![screenshot_20181201_155519](https://user-images.githubusercontent.com/840070/49332802-c507a900-f581-11e8-85bc-1d1c3460af3f.png)

**Comment by llelectronics** [comment]
This needed a new fontconfig subdirectory with fonts.conf file: https://github.com/netrunner-common/netrunner-settings-theming/commit/98c367781fd5db71226e51d7291ddc8bf2fc8dcc
