### ISSUE TITLE
add package default: "web-menu-entries"

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#72]

**Comment by star-buck** [comment]
reopened for Rolling

**Comment by NuLogicSystems** [comment]
I packaged this, installed the package, and they show up under lost and found.
![Screenshot_20190401_142208](https://user-images.githubusercontent.com/10186587/55350260-a7901080-5489-11e9-967b-9cc445a3aa27.png)

**Comment by llelectronics** [comment]
You need to install each desktop file into the new category. See this postinst we use on Netrunner (Debian) https://github.com/dci-extras-packaging/web-menu-entries/blob/master/debian/postinst

**Comment by star-buck** [comment]
Just trying this, there might be an easier, more integrated way that
Manjaro ships lately called JAK, Jade Application Framework. Will test in
on Rolling, if it works great there, we could look into shipping it on
Debian.

**Comment by NuLogicSystems** [comment]
@llelectronics,
Duh, fixed it.

@star-buck,
Do you mean the jade application kit?
https://github.com/codesardine/Jade-Application-Kit

**Comment by star-buck** [comment]
Yes, that one.
