### ISSUE TITLE
packages: discover is missing

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#73]

**Comment by llelectronics** [comment]
I think this is the wrong issue tracker (as it is for Plasma 5.14). Anyway for netrunner we tend to remove discover in the end. I changed that so the next ISO should have it.

**Comment by llelectronics** [comment]
Now we have 2 update icons in the systray. One from discover and one from mintupdate. 
We need to decide which one to keep.

**Comment by star-buck** [comment]
Mintupdate

**Comment by llelectronics** [comment]
Plasma Discover Notifier should be disabled now with this commit: https://github.com/netrunner-artwork/artwork-lnf-theme-netrunner-desktop/commit/6a39e38cda23345b836170d4338ed886b44cc2a8

**Comment by star-buck** [comment]
please label stuff fixed green, thanks.
