### ISSUE TITLE
Firefox: set shockwave to always active, h264 to activate to install the codec

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#76]
i guess skype-web app needs the latter to be installed for webrtc:
![screenshot_20181208_164215](https://user-images.githubusercontent.com/840070/49687766-2098e000-fb08-11e8-9aa0-052cdf339a02.png)

**Comment by llelectronics** [comment]
Codec should be installed and working. 
The Flash thing needs further configuration changes and is not ready yet.
