### ISSUE TITLE
Firefox: it seems the plasma version is severly broken

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#79]
- "Edit" from github doesnt work, it does not update to make the field editable
- github dropdowns like Assignees or Labels dont work
- "playing music" in nextcloud doesnt work
- some videos dont work
 and more.
Not sure why it is so horribly broken all of a sudden...maybe related to the firefox plasma integration? did we install the plugin from Kai Uwe btw.?

So we can try finding out why this happens and fix it or switching back to unplasmified version and see if it works better then, losing the dialog and integration.

**Comment by shadeslayer** [comment]
@leszek did you ship the Ubuntu version on Debian?
