### ISSUE TITLE
/usr/share/sddm/themes shows Breeze and Maui folders installed, but both are empty (Breeze should be installed, we can remove Maui though completely)

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#81]
![screenshot_20181208_192611](https://user-images.githubusercontent.com/840070/49689266-4bdaf980-fb1f-11e8-8f00-ec915f4c5bce.png)

**Comment by llelectronics** [comment]
They aren't actually empty and ship a configuration for setting the default wallpaper for those themes. You requested that in the past.

**Comment by star-buck** [comment]
it made sense when we actually shipped both breeze and maui sddm in the past.
Now installing package "sddm-theme-breeze" leads to two entries:
![screenshot_20181223_175538](https://user-images.githubusercontent.com/840070/50385805-fc2e2d80-06db-11e9-90e4-daf85d9d6960.png)
I therefore suggest to remove those two folders and add "sddm-theme-breeze" theme normally again.
