### ISSUE TITLE
Desktop: Readme: point to "http://www.netrunner.com/readme-debian"

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#82]

**Comment by llelectronics** [comment]
Really http only or better https? 
**edit: I'll add the https stuff as http is redirecting anyway**

**Comment by llelectronics** [comment]
Done: https://github.com/netrunner-desktop/netrunner-desktop-settings-desktop/commit/bf213206d9eaac5b2c64467d131d826e3edeb3ad
