### ISSUE TITLE
gtk2-settings-kcm: breeze dark not fully applied

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#84]
the preview shows this:
![screenshot_20181209_122135](https://user-images.githubusercontent.com/840070/49696645-5d6ae280-fbad-11e8-8b4b-fdcc695e4d54.png)
but apps menus are still like this even after reboot:
![screenshot_20181209_122615](https://user-images.githubusercontent.com/840070/49696679-dc601b00-fbad-11e8-950e-64f3d749187b.png)
![screenshot_20181209_122712](https://user-images.githubusercontent.com/840070/49696680-dc601b00-fbad-11e8-803c-aacbe3c49aaa.png)
![screenshot_20181209_122746](https://user-images.githubusercontent.com/840070/49696681-dc601b00-fbad-11e8-919d-ac32711cf69d.png)

could be we have netrunner gtk configs somewhere preventing a clean change from breeze to something else?

**Comment by llelectronics** [comment]
Yeah had the same issue on Neptune aswell. The issue comes from the way we ship the gtk settings.
We ship them in **/etc/gtk-{2,3}-0** as a global setting. Apparently whatever we set in there as gtk-theme has priority over whatever is set for the user in **~/.config** 
@shadeslayer I would suggest switching back to shipping those gtk config in **/etc/skel/** again to "fix it" for now. It smells like a bug to me that /etc/gtk~ stuff is overprioritized though I am not sure where to even look at and if it isn't maybe a wanted behavior.

**Comment by star-buck** [comment]
@kbroulik : do you know if this is intended or a bug?
in any case, we need this to be working wether we default ship a dark theme (which i am testing for "blackbird") or light theme and the people want to switch themselves

**Comment by shadeslayer** [comment]
Shipping a file in skel would break themeing customisations for GTK apps
that require root, like synaptic.

On a more serious note, what the fuck GTK?

**Comment by star-buck** [comment]
well, gnome devs dont seem to care much about themeing in general these days...
we still need to fix this, but synaptic root did also not change selecting a dark theme with current iso?

**Comment by star-buck** [comment]
removing the etc/gtk* folders does fix the issues, and i think the synaptic not changing themes is the lesser error at this point (it does look better without breeze even imo and seems to have fixed the multiple entires issue, or was that fixed by something else)?

**Comment by kbroulik** [comment]
> do you know if this is intended or a bug?

I would have assumed user settings to override system settings as in KDE but apparently Gnome is special again :)
Shouldn't kde-gtk-config which writes into gtk2 and 3 settings be enough with no /etc/skel changes required? Or even just "krdb" (plasma-desktop) which syncs Plasma colors to Gtk colors?

**Comment by llelectronics** [comment]
For now moved the gtk theme settings to skel again: https://github.com/netrunner-common/netrunner-settings-theming/commit/a78f3d340622b6550b7c5b6f883205585cd698ec
