### ISSUE TITLE
Lookandfeel: Rename "Netrunner Black X" to "Netrunner Default", rename Netrunner Blue X to "Netrunner Blue"

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#85]
this in preparation of a new "Netrunner Black" theme (without the X)

**Comment by llelectronics** [comment]
We have a Netrunner Desktop LNF already which is always the default loaded by plasma.
Should we really rename Netrunner Black X to Netrunner ? Maybe we can leave the name and change it accordingly to the Blue simple Netrunner Black. 
The new theme we can call and add as Netrunner Dark?
Also for the sake of upgrading easily the package names for the blue x and black x package won't change anyway.

**Comment by star-buck** [comment]
Black is not really Black, and the new theme should be called Black to due Blackbird.
So yes, lets rename the Netrunner BlackX to "Netrunner" or "Netrunner Default", or if the current LNF is actually restoring the theme to be like this, we can remove blackx and name that theme "Netrunner Default"?

**Comment by llelectronics** [comment]
So the current BlackX stays the default look and feel in netrunner? Then of course we could rename it to "Netrunner default" in the menu. Though the paths and package name needs to stay blackx otherwise the risk is very high it might break something for people who upgrade

**Comment by llelectronics** [comment]
Reanmed it now here: https://github.com/ds9-artwork/lnf-theme-blackx/commit/8e109596b5efd4f57a438bdca3fb0f957b08ed6e

**Comment by star-buck** [comment]
now what exactly is the difference between Netrunner Desktop and Netrunner Default?
![screenshot_20181214_224651](https://user-images.githubusercontent.com/840070/50029134-30299480-fff2-11e8-8d4d-950dd0c345d3.png)

**Comment by star-buck** [comment]
if both are the same, we could remove "Netrunner Default" and only leave Netrunner Desktop?

**Comment by llelectronics** [comment]
Almost the same. The Desktop one also contains the setup scripts for setting up the panel and desktop containment.

**Comment by star-buck** [comment]
if we can safely get rid of Netrunner Default, then lets do that.
