### ISSUE TITLE
new lookandfeel: "Netrunner Black"

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#88]
- desktop theme: alphablack: https://www.opendesktop.org/p/1084931/
- icons: obsidian: https://www.opendesktop.org/p/1169579/
- widget style: kvantum
- colors: KvantumAlt
- gtk2/3 theme: breezedark, tick prefer dark theme
- windo decoration: FormaN : https://www.opendesktop.org/p/1002712/
----

**Comment by star-buck** [comment]
add this new LNF theme "Netrunner Black" in a way that it doesnt interfere with the "old" Netrunner LNF, so one can switch back and forth between the two.

**Comment by llelectronics** [comment]
LNF does not allow to set the GTK Theme.

**Comment by llelectronics** [comment]
@star-buck do we need to package all the different icon theme variants that obsidian ships with (e.g. obsidian-amber, obsidian-amber-light,obsidian-green,...)  or is it just enough to ship the main one?

**Comment by star-buck** [comment]
The main one is fine, though i dont mind shipping the package as is.

**Comment by llelectronics** [comment]
I am just a bit concerned because it will clutter the list of icon themes with 35 different variants of obsidian and also leaving them out helps us reducing the ISO size if we ship the icon theme by default on the ISO.

**Comment by star-buck** [comment]
Sure, then just the default one.

**Comment by llelectronics** [comment]
New LNF is now available as package **artwork-lnf-theme-netrunner-black**. 
Should this be shipped by default on the ISO?

**Comment by star-buck** [comment]
in case of the new iso yes, default.

**Comment by star-buck** [comment]
works great, now only needs to be default activated.

**Comment by llelectronics** [comment]
Not fully applied yet as default on latest ISO. Seems like setting the LNF alone does not work. I need to also edit the default settings to match the LNF theme :/ (so Kwin decoration, widget style are wrong)
