### ISSUE TITLE
pulseaudio: edit /etc/pulse/default.pa

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#91]
Edit the file /etc/pulse/default.pa:
Find the following line and add tsched=0 at the end:

> load-module module-udev-detect tsched=0

**Comment by llelectronics** [comment]
Added this should land on next ISO: https://github.com/ds9-common/default-settings-pulseaudio/commit/f28d22479f3975dcea80de2c41036dc808e029bb
