### ISSUE TITLE
FF: after starting it a second time, error message appears

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#92]
![screenshot_20181212_140205](https://user-images.githubusercontent.com/840070/49871541-d02ac680-fe16-11e8-88fd-53f5bc4f99aa.png)

**Comment by llelectronics** [comment]
This commit fixes this: https://github.com/netrunner-common/netrunner-settings-firefox/commit/9b6382fdde16cbedc1a029bfebb9ff05f1cf4c74
Should land on next ISO.

**Comment by notuxius** [comment]
No longer reproducible for me on 12.12 updated iso and on installed system after updates
