### ISSUE TITLE
sddm: change cursor to white-classicia

### ISSUE THREAD

**Issue by notuxius** [blue-systems/netrunner-issues-old#95]
Currently Breeze and then white-classicia mouse cursors are displayed upon loading of Debian Netrunner and windows and then white-classicia mouse cursor upon loading of Netrunner Rolling - display only one of them - white-classicia for more consistency

**Comment by shadeslayer** [comment]
@llelectronics we'll need to adjust the sddm hook for the live session for this on the ISO I believe.

**Comment by shadeslayer** [comment]
As well as fixing https://github.com/netrunner-common/netrunner-settings-sddm/blob/master/etc/sddm.conf#L3 to say classica

**Comment by star-buck** [comment]
This ones not superimportant though.
